# Use root/example as user/password credentials

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: my_user
      MARIADB_PASSWORD: my_pass
      MARIADB_DATABASE: ap_quiz
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
